# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190201_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 3, 59, 20, 319360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 3, 59, 20, 318044, tzinfo=utc)),
        ),
    ]
