# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190201_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 14, 35, 45, 709988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 14, 35, 45, 708604, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
